apiVersion: v1
kind: Namespace
metadata:
  name: modelstorage
  labels:
    name: modelstorage
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: modelstorage
  namespace: modelstorage
spec:
  bucketName: modelstorage
  storageClassName: openshift-storage.noobaa.io